on:
  workflow_call:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      
      #      - uses: ./.github/actions/setup-node

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      
      - name: Install node 20
        uses: actions/setup-node@v4
        with:
          node-version: '>=20'
          cache: 'pnpm'

      - name: Create Project
        id: createProject
        uses: ./action.yml
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: donaldfoss-scc_setup-sonar-action
          SONAR_ORGANIZATION: donaldfoss-scc

      - name: Run tests
        run: |
          pnpm install && pnpm test:coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=${{steps.createProject.outputs.SONAR_ORGANIZATION}}
            -Dsonar.projectKey=${{steps.createProject.outputs.SONAR_PROJECT_KEY}}
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.qualitygate.wait=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
